import { hero } from '../content/hero'
const A='/assets/stickers/'
function Wave({ tone='cream' }:{tone?:'cream'|'red'|'yellow'}){return <div className={`wave wave-${tone}`} aria-hidden="true"><span/><span/></div>}
function Food({name, className='' }:{name:string,className?:string}){return <img className={`food-sticker ${className}`} src={A+name} alt="" aria-hidden="true" decoding="async"/>}
export function Story(){return <main id="wrap" className="story">
  <section className="feel-good section-red"><Wave/><p className="eyebrow">COOKED LOUD. WRAPPED TIGHT.</p><h2>FOOD THAT<br/>FEELS GOOD</h2><div className="feel-wrap"><Food name="wrapped-shawarma.png"/><Food name="chicken.png" className="mini chicken"/><Food name="tomato.png" className="mini tomato"/></div><div className="callout callout-left">FRESH CHICKEN<br/>FULL OF FLAVOUR</div><div className="callout callout-right">HOT OFF THE SPIT<br/>SHAWARMA SAUCE</div><Wave tone="cream"/></section>
  <section className="quality section-cream"><div className="ingredient-row"><Food name="chicken.png"/><Food name="lettuce.png"/><Food name="tomato.png"/><Food name="pickles.png"/><Food name="flatbread.png"/><Food name="wrapper-paper.png"/></div><p className="eyebrow red">PURE QUALITY</p><h2>EVERY DAY.<br/>PACKED WITH<br/><em>REAL</em> FLAVOUR.</h2><p className="under-copy">The kind of wrap you plan your afternoon around.</p><Wave tone="yellow"/></section>
  <section className="story-bites section-yellow"><p className="eyebrow red">A STORY IN EVERY BITE.</p><p className="intro">From the grill to your hands, every wrap has a little madness in it.</p><div className="bite-list"><article><Food name="spit.png"/><div><b>THE GRILL</b><span>Charred, juicy, non-negotiable.</span></div></article><article><Food name="rolled-wrap.png"/><div><b>THE ROLL</b><span>Warm flatbread, folded tight.</span></div></article><article><Food name="wrapped-shawarma.png"/><div><b>THE BITE</b><span>Big flavour. Zero boring.</span></div></article></div><Wave tone="cream"/></section>
  <section className="flavour section-cream"><p className="eyebrow red">FEEL THE FLAVOUR</p><p>Garlic, crunch, heat and a whole lot of chicken. Everything that belongs in a proper wrap, nothing that doesn’t.</p><div className="flavour-strip"><Food name="fries.png"/><Food name="wrapped-shawarma.png"/><Food name="pickles.png"/></div><Wave tone="cream"/></section>
  <footer className="footer"><div className="footer-food"><Food name="lettuce.png"/><Food name="tomato.png"/><Food name="wrapped-shawarma.png"/><Food name="flatbread.png"/></div><img src="/assets/mady-logo.png" alt="Mady" width="220" height="92" decoding="async"/><p>MADLY GOOD • HALAL • LOUD FLAVOUR</p><p>OPEN DAILY • DHAKA • COME HUNGRY</p></footer>
</main>}
